/** Paiements SumUp Cardoria — Boutique et Live Admin. */
import crypto from "crypto";
import { logAudit } from "../audit.js";
import { readJson, writeJson } from "../storage.js";
import { applyLivePaymentStatus } from "../live/sessions.js";
import { recordPayment, getPaymentByCheckoutId, updatePayment } from "./ledger.js";
import { makePaymentId } from "./migrate.js";
const SUMUP_API=process.env.SUMUP_API_BASE||"https://api.sumup.com",money=n=>Math.round(Number(n||0)*100)/100;
export function isSumUpConfigured(){return!!(process.env.SUMUP_API_KEY&&process.env.SUMUP_MERCHANT_CODE);}
async function sumupRequest(method,p,b){if(!process.env.SUMUP_API_KEY)throw Object.assign(new Error("SUMUP_API_KEY non configurée"),{status:503});const r=await fetch(`${SUMUP_API}${p}`,{method,headers:{Authorization:`Bearer ${process.env.SUMUP_API_KEY}`,"Content-Type":"application/json",Accept:"application/json"},body:b?JSON.stringify(b):undefined}),t=await r.text();let d={};try{d=t?JSON.parse(t):{};}catch{d={raw:t};}if(!r.ok)throw Object.assign(new Error(d.message||d.error_message||d.detail||t||`SumUp HTTP ${r.status}`),{status:r.status});return d;}
export function mapSumUpStatus(status){const s=String(status||"").toUpperCase();if(["PAID","SUCCESSFUL","SUCCESS"].includes(s))return"paid";if(["FAILED","DECLINED","CANCELLED","CANCELED"].includes(s))return"failed";if(s==="REFUNDED")return"refunded";return"pending";}
export async function retrieveSumUpCheckout(id){return sumupRequest("GET",`/v0.1/checkouts/${encodeURIComponent(id)}`);}
export async function createSumUpCheckout({orderId,amount,description,customerEmail,redirectUrl,returnUrl,source="boutique"}){if(!isSumUpConfigured())throw Object.assign(new Error("SumUp non configuré — définir SUMUP_API_KEY et SUMUP_MERCHANT_CODE"),{status:503});const payload={checkout_reference:orderId,amount:money(amount),currency:"EUR",merchant_code:process.env.SUMUP_MERCHANT_CODE,description:description||`Commande Cardoria ${orderId}`,redirect_url:redirectUrl,hosted_checkout:{enabled:true}};if(returnUrl)payload.return_url=returnUrl;if(customerEmail)payload.customer_email=customerEmail;const c=await sumupRequest("POST","/v0.1/checkouts",payload),paymentId=makePaymentId();recordPayment({id:paymentId,orderId,source,sumupCheckoutId:c.id,amount:payload.amount,status:mapSumUpStatus(c.status),customerEmail:customerEmail||"",description:payload.description,metadata:{checkoutReference:orderId}});logAudit({type:"payment",action:"sumup_checkout_created",user:customerEmail||"client",detail:`${orderId} — ${c.id}`});return{checkoutId:c.id,sessionId:c.id,providerOrderId:c.id,url:c.hosted_checkout_url,status:mapSumUpStatus(c.status),paymentId,environment:"production"};}
function applyBoutique(orderId,status,{checkoutId,transactionId,paymentMethod}={}){const orders=readJson("orders",[]),i=orders.findIndex(o=>o.id===orderId);if(i<0)return null;const o=orders[i],previous=o.paymentStatus;if(previous==="paid"&&status!=="refunded")return{...o,alreadyPaid:true};if(previous===status)return{...o,duplicate:true};o.paymentStatus=status;o.payment={pending:"En attente SumUp",paid:"Payé SumUp (CB)",failed:"Paiement échoué",refunded:"Remboursé SumUp"}[status]||o.payment;o.sumupCheckoutId=checkoutId||o.sumupCheckoutId;o.paymentProviderOrderId=o.sumupCheckoutId;o.sumupTransactionId=transactionId||o.sumupTransactionId;o.paymentProviderTransactionId=o.sumupTransactionId;o.paymentMethod=paymentMethod||"sumup_card";o.updatedAt=new Date().toISOString();if(status==="paid"&&previous!=="paid")o.status="À préparer";if(status==="failed")o.status="Paiement échoué";if(status==="refunded")o.status="Remboursée";writeJson("orders",orders);return o;}
function applyCardoriaStatus(orderId,status,patch){if(String(orderId||"").startsWith("LCK-"))return applyLivePaymentStatus(orderId,status,{paymentProviderOrderId:patch.checkoutId,paymentProviderTransactionId:patch.transactionId});return applyBoutique(orderId,status,patch);}
export async function syncPaymentFromCheckout(checkoutId){const checkout=await retrieveSumUpCheckout(checkoutId),status=mapSumUpStatus(checkout.status),tx=checkout.transactions?.[0],transactionId=tx?.id||tx?.transaction_code||checkout.transaction_code||"",payment=getPaymentByCheckoutId(checkoutId),orderId=payment?.orderId||checkout.checkout_reference;if(payment)updatePayment(payment.id,{status,sumupTransactionId:transactionId,paymentMethod:tx?.payment_type||"sumup_card"});const order=applyCardoriaStatus(orderId,status,{checkoutId,transactionId,paymentMethod:tx?.payment_type||"sumup_card"});return{checkout,status,transactionId,payment:getPaymentByCheckoutId(checkoutId),orderId,order};}
export function verifySumUpWebhookSignature(rawBody,signatureHeader){const secret=process.env.SUMUP_WEBHOOK_SECRET;if(!secret||!signatureHeader)return!secret;const expected=crypto.createHmac("sha256",secret).update(rawBody).digest("hex"),sig=String(signatureHeader).replace(/^sha256=/i,"").trim();try{return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected));}catch{return false;}}
export async function handleSumUpWebhook(rawBody,signatureHeader){if(process.env.NODE_ENV==="production"&&!process.env.SUMUP_WEBHOOK_SECRET)throw Object.assign(new Error("SUMUP_WEBHOOK_SECRET obligatoire en production"),{status:503});if(process.env.SUMUP_WEBHOOK_SECRET&&!verifySumUpWebhookSignature(rawBody,signatureHeader))throw Object.assign(new Error("Signature webhook SumUp invalide"),{status:401});let event={};try{event=JSON.parse(rawBody.toString());}catch{throw Object.assign(new Error("Payload webhook invalide"),{status:400});}const checkoutId=event.id||event.checkout_id||event.data?.id||event.payload?.checkout_id;if(!checkoutId)return{received:true,ignored:true};const result=await syncPaymentFromCheckout(checkoutId);logAudit({type:"payment",action:"sumup_webhook",user:"system",detail:`${checkoutId} → ${result.status}`});return{received:true,checkoutId,...result};}
export const createPaymentLink=createSumUpCheckout;
