
(function(){
"use strict";
const BACKEND_URL="https://cardoria-site-2.onrender.com";
const ADMIN_CODE_LOCAL="CARDORIA59330";
let allProducts=[], allOrders=[], cart=[], productFilter="all", orderFilter="all";
function qs(id){return document.getElementById(id)}
function euro(n){return Number(n||0).toFixed(2).replace(".",",")+" €"}
function todayStr(){return new Date().toISOString().slice(0,10)}
async function loadJSON(url,fallback){try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("not found");return await r.json()}catch(e){return fallback}}
function toggleMenu(){const menu=qs("menu");if(menu)menu.classList.toggle("open")}
async function initCardoria(){if(!window.CardoriaAttribution)trackPageView();allProducts=await loadJSON("products.json",[]);allOrders=await loadJSON("orders.json",[]);renderProducts();renderCart();renderStock();renderOrders();renderDocument();renderDashboard();renderAnalytics();protectAdmin();initCardAutocomplete();prefillEstimationCard();confirmBoutiqueReturn()}
function setFilter(f){productFilter=f;renderProducts()}
function renderProducts(){const box=qs("products");if(!box)return;const search=(qs("search")?.value||"").toLowerCase();const list=allProducts.filter(p=>(productFilter==="all"||p.category===productFilter)&&p.name.toLowerCase().includes(search));box.innerHTML=list.map(p=>`<article class="product"><div class="product-img">${p.emoji||"🃏"}</div><h3>${p.name}</h3><p>${p.condition} • Stock : ${p.stock}</p><div class="price">${euro(p.price)}</div><button class="primary" type="button" onclick="addToCart('${p.id}')" ${p.stock<=0?"disabled":""}>Ajouter au panier</button></article>`).join("")}
function addToCart(id){const p=allProducts.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...p,qty:1});renderCart()}
function renderCart(){const box=qs("cart"),total=qs("cartTotal");if(!box||!total)return;box.innerHTML=cart.map(i=>`<li>${i.qty} x ${i.name} - ${euro(i.qty*i.price)}</li>`).join("")||"<li>Panier vide</li>";total.textContent=euro(cart.reduce((s,i)=>s+i.qty*i.price,0))}
async function checkoutBoutique(){if(!cart.length){alert("Panier vide.");return}const email=qs("shopEmail")?.value?.trim();const name=qs("shopName")?.value?.trim()||"";if(!email){alert("Indiquez votre email pour payer.");return}const items=cart.map(i=>({ref:i.id,name:i.name,qty:i.qty,price:i.price}));const attr=window.CardoriaAttribution?CardoriaAttribution.getPayload():{};try{const r=await fetch(`${BACKEND_URL}/api/payments/boutique/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerEmail:email,customerName:name,items,shippingCost:0,shipping:"Standard",successUrl:location.origin+location.pathname,...attr})});const d=await r.json();if(!d.ok){alert(d.error||"Paiement SumUp indisponible.");return}if(d.url)location.href=d.url;else alert("Lien de paiement SumUp non reçu.")}catch(e){alert("Erreur : "+e.message)}}
function confirmBoutiqueReturn(){const p=new URLSearchParams(location.search);if(!p.get("paid"))return;const order=p.get("order");const msg=qs("shopPayMsg");if(msg)msg.textContent=order?"Merci ! Commande "+order+" — confirmation SumUp en cours.":"Paiement SumUp reçu.";cart=[];renderCart()}
function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function sanitizeClientResult(text){if(!text)return"";return String(text).replace(/SCORE_CONFIANCE\s*:\s*\d+/gi,"").replace(/score d['']authenticit[eé][^\n]*/gi,"").replace(/(?:niveau|indice|taux)\s+(?:de\s+)?confiance[^\n]*/gi,"").replace(/confiance\s*(?:d['']authenticit[eé])?\s*[:\-]?\s*\d+\s*%/gi,"").replace(/prix de rachat[^\n]*/gi,"").replace(/rachat cardoria[^\n]*/gi,"").replace(/marge estim[eé]e[^\n]*/gi,"").replace(/marge[^\n]*%/gi,"").replace(/revente conseill[eé]e[^\n]*/gi,"").replace(/prix de revente[^\n]*/gi,"").replace(/cardoria market score[^\n]*/gi,"").replace(/recommandation[^\n]*/gi,"").replace(/acheter imm[eé]diatement[^\n]*/gi,"").replace(/vendre aux ench[eè]res[^\n]*/gi,"").replace(/produit premium[^\n]*/gi,"").replace(/\n{3,}/g,"\n\n").trim()}
async function sendCardEstimate(){const result=qs("estimateResult");if(!result){alert("Zone résultat introuvable.");return}result.innerHTML="<p>Analyse IA Cardoria en cours…</p>";try{const files=Array.from(qs("cardFiles")?.files||[]);const imagesBase64=[];for(const file of files.slice(0,6)){imagesBase64.push(await fileToBase64(file))}const attr=window.CardoriaAttribution?CardoriaAttribution.getPayload():{};const payload={customerName:qs("customerName")?.value||"",customerEmail:qs("customerEmail")?.value||"",cardName:qs("cardName")?.value||"",cardGame:qs("cardGame")?.value||"",cardNotes:qs("cardNotes")?.value||"",cardId:qs("cardId")?.value||"",cardCondition:qs("cardCondition")?.value||"nm",imagesBase64,...attr};const response=await fetch(`${BACKEND_URL}/api/estimation-carte`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let data;try{data=await response.json()}catch{throw new Error("Réponse serveur illisible.")}if(!response.ok||!data.ok){result.textContent="Erreur : "+(data.error||data.details||"Analyse impossible.");return}const clean=sanitizeClientResult(data.clientResult||data.result);data.clientResult=clean;if(window.CardoriaAI){CardoriaAI.renderAiResult(result,data)}else{result.textContent=clean}}catch(e){result.textContent="Erreur de connexion au système Cardoria : "+e.message}}
function initCardAutocomplete(){const input=qs("cardName");const box=qs("cardSuggest");const hidden=qs("cardId");if(!input||!box)return;const cLicenseMap={pokemon:"Pokémon",yugioh:"Yu-Gi-Oh!",onepiece:"One Piece",lorcana:"Lorcana",magic:"Magic",dragonball:"Dragon Ball",starwars:"Star Wars Unlimited",sports:"Autre"};let timer=null;input.addEventListener("input",function(){hidden&&(hidden.value="");clearTimeout(timer);const q=input.value.trim();if(q.length<2){box.classList.remove("open");box.innerHTML="";return}timer=setTimeout(function(){fetch(`${BACKEND_URL}/api/engine/cards/search?q=${encodeURIComponent(q)}&limit=8`).then(r=>r.json()).then(function(d){const list=d.results||[];if(!list.length){box.classList.remove("open");return}box.innerHTML=list.map(function(c){return `<button type="button" data-id="${c.id}" data-name="${c.name}" data-license="${c.license}">${c.imageThumb?`<img src="${c.imageThumb}" alt="">`:"🃏"} <span>${c.name} — ${c.extension} (${c.number})</span></button>`}).join("");box.classList.add("open");box.querySelectorAll("button").forEach(function(btn){btn.onclick=function(){input.value=btn.dataset.name;hidden.value=btn.dataset.id;box.classList.remove("open");const game=qs("cardGame");if(game&&cLicenseMap[btn.dataset.license])game.value=cLicenseMap[btn.dataset.license]}})})},280)})};document.addEventListener("click",function(e){if(!e.target.closest(".engine-autocomplete")){const b=qs("cardSuggest");if(b)b.classList.remove("open")}});function prefillEstimationCard(){const id=new URLSearchParams(location.search).get("card");if(!id)return;fetch(`${BACKEND_URL}/api/engine/cards/${encodeURIComponent(id)}`).then(r=>r.json()).then(function(d){if(!d.card)return;const n=qs("cardName"),h=qs("cardId");if(n)n.value=d.card.name;if(h)h.value=d.card.id})}
function trackPageView(){if(location.pathname.includes("admin"))return;if(window.CardoriaAttribution){window.CardoriaAttribution.trackPageView();return}const device=window.innerWidth<768?"mobile":window.innerWidth<1024?"tablet":"desktop";fetch(`${BACKEND_URL}/api/analytics/track`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page:location.pathname+location.search,referrer:document.referrer||"direct",device})}).catch(function(){})}
function protectAdmin(){const page=location.pathname.split("/").pop();const protectedPages=["admin.html","admin-comptabilite.html","admin-utilisateurs.html","admin-statistiques.html","admin-journal.html","admin-integrations.html","admin-catalogue.html","admin-marketplace.html","admin-ia.html","admin-performance-ia.html","admin-ai-enterprise.html","admin-ultimate.html","admin-bigdata.html","admin-sante.html","admin-marche.html","admin-scanner.html","admin-paiements.html","admin-seo.html","admin-commandes.html","admin-stock.html","admin-analytics.html","admin-estimations.html"];if(protectedPages.includes(page)&&sessionStorage.getItem("cardoria_admin_connected")!=="yes"){location.href="admin-login.html"}}
async function adminLogin(){const err=qs("loginError");if(err)err.textContent="";const email=qs("adminEmail")?.value?.trim();const password=qs("adminPassword")?.value||"";const totpCode=qs("adminTotp")?.value?.trim()||"";const legacyCode=qs("adminCode")?.value?.trim();if(email&&password){try{const r=await fetch(`${BACKEND_URL}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,totpCode})});const d=await r.json();if(d.requires2fa&&!totpCode){const totp=qs("adminTotpRow");if(totp)totp.style.display="block";if(err)err.textContent="Code 2FA requis.";return}if(!d.ok){if(err)err.textContent=d.error||"Connexion impossible.";return}sessionStorage.setItem("cardoria_admin_connected","yes");sessionStorage.setItem("cardoria_session_token",d.token);if(d.csrfToken)sessionStorage.setItem("cardoria_csrf_token",d.csrfToken);if(d.user?.email)sessionStorage.setItem("cardoria_admin_email",d.user.email);location.href="admin.html"}catch(e){if(err)err.textContent="Erreur réseau : "+e.message}return}if(legacyCode){if(legacyCode===ADMIN_CODE_LOCAL||legacyCode===sessionStorage.getItem("cardoria_admin_code")){sessionStorage.setItem("cardoria_admin_connected","yes");sessionStorage.setItem("cardoria_admin_code",legacyCode);location.href="admin.html";return}try{const r=await fetch(`${BACKEND_URL}/api/auth/legacy`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:legacyCode})});const d=await r.json();if(d.ok){sessionStorage.setItem("cardoria_admin_connected","yes");sessionStorage.setItem("cardoria_admin_code",legacyCode);location.href="admin.html";return}}catch(e){/* ignore */}if(err)err.textContent="Code incorrect.";return}if(err)err.textContent="Indiquez email/mot de passe ou code legacy."}
function adminLogout(){const token=sessionStorage.getItem("cardoria_session_token");if(token){fetch(`${BACKEND_URL}/api/auth/logout`,{method:"POST",headers:{Authorization:"Bearer "+token}}).catch(function(){})}sessionStorage.removeItem("cardoria_admin_connected");sessionStorage.removeItem("cardoria_session_token");sessionStorage.removeItem("cardoria_csrf_token");sessionStorage.removeItem("cardoria_admin_code");sessionStorage.removeItem("cardoria_admin_email");location.href="index.html"}
function renderStock(){const rows=qs("stockRows");if(!rows)return;rows.innerHTML=allProducts.map(p=>`<tr><td>${p.id}</td><td>${p.name}</td><td>${p.category}</td><td>${p.condition}</td><td>${euro(p.price)}</td><td>${p.stock}</td><td>${p.stock>0?"Disponible":"Rupture"}</td></tr>`).join("")}
function orderTotal(o){return(o.items||[]).reduce((s,i)=>s+i.qty*i.price,0)}
function setOrderFilter(f){orderFilter=f;renderOrders()}
function statusSteps(current){const steps=["À préparer","En préparation","Expédiée","Livrée","Facturée"];const idx=steps.indexOf(current);return steps.map((s,i)=>`<span class="${i<=idx?"active":""}">${s}</span>`).join("")}
function renderOrders(){const box=qs("orderCards");if(!box)return;const q=(qs("orderSearch")?.value||"").toLowerCase();const list=allOrders.filter(o=>{const ok=orderFilter==="all"||(orderFilter==="today"?o.date===todayStr():o.status===orderFilter);const txt=(o.id+o.client+o.email+o.status+(o.tracking||"")).toLowerCase();return ok&&txt.includes(q)});box.innerHTML=list.map(o=>`<article class="request-card"><div class="request-head"><div><h3>${o.id}</h3><p>${o.date} • ${o.client}<br>${o.email}</p></div><strong>${euro(orderTotal(o))}</strong></div><div class="progress">${statusSteps(o.status)}</div><p><b>Livraison :</b> ${o.shipping||"À définir"} • <b>Suivi :</b> ${o.tracking||"Non renseigné"} • <b>Paiement :</b> ${o.payment}</p><div class="actions no-print"><button type="button" onclick="openOrderDoc('${o.id}','bon')">Bon commande</button><button type="button" onclick="openOrderDoc('${o.id}','facture')">Facture</button></div></article>`).join("")||"<div class='panel'>Aucune commande.</div>"}
function openOrderDoc(id,type){window.open(`document-commande.html?id=${encodeURIComponent(id)}&type=${encodeURIComponent(type)}`,"_blank")}
function renderDocument(){const page=qs("documentPage");if(!page)return;const params=new URLSearchParams(location.search);const id=params.get("id");const type=params.get("type")||"bon";const o=allOrders.find(x=>x.id===id)||allOrders[0];if(!o){page.innerHTML="<h1>Commande introuvable</h1>";return}const rows=(o.items||[]).map(i=>`<tr><td>${i.ref}</td><td>${i.name}</td><td>${i.qty}</td><td>${euro(i.price)}</td><td>${euro(i.qty*i.price)}</td></tr>`).join("");page.innerHTML=`<section class="panel"><div class="request-head"><div><h1>${type==="facture"?"FACTURE":"BON DE COMMANDE"}</h1><p>${o.id}</p></div><img src="/assets/logo/cardoria-premium.png" style="width:130px" alt="Cardoria" onerror="this.onerror=null;this.src='/logo-cardoria.jpg'"></div><div class="grid"><div><h3>Cardoria</h3><p>Email : Cardoria59330@gmail.com</p></div><div><h3>Client</h3><p>${o.client}<br>${o.email}<br>${o.address||""}</p></div><div><h3>Livraison</h3><p>${o.shipping||""}<br>${o.tracking||"Suivi à renseigner"}</p></div></div><div class="table-wrap"><table><thead><tr><th>Réf.</th><th>Désignation</th><th>Qté</th><th>Prix</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table></div><h2>Total : ${euro(orderTotal(o))}</h2><button class="primary no-print" type="button" onclick="window.print()">Imprimer / PDF</button></section>`}
function renderDashboard(){if(!qs("dashOrders"))return;const today=allOrders.filter(o=>o.date===todayStr());qs("dashOrders").textContent=today.length;qs("dashRevenue").textContent=euro(today.reduce((s,o)=>s+orderTotal(o),0));qs("dashPending").textContent=allOrders.filter(o=>["À préparer","En préparation"].includes(o.status)).length;qs("dashStock").textContent=allProducts.reduce((s,p)=>s+p.stock,0)}
async function loadAdminEstimations(){const box=qs("estimationsList");if(!box)return;box.innerHTML="<div class='panel'>Chargement...</div>";try{const code=qs("adminCodeEstimations")?.value||ADMIN_CODE_LOCAL;const response=await fetch(`${BACKEND_URL}/api/admin/estimations`,{headers:{"x-cardoria-admin-code":code}});const data=await response.json();if(!data.ok){box.innerHTML=`<div class="panel">Erreur : ${data.error}</div>`;return}box.innerHTML=(data.requests||[]).map(x=>`<article class="request-card"><h3>${x.id}</h3><p>${x.customerName} • ${x.customerEmail}<br>${x.cardGame} • ${x.cardName}${x.confidenceScore!=null?`<br><b>Score confiance (admin) :</b> ${x.confidenceScore}%`:x.suspicionAlert?`<br><b>Alerte contrefaçon envoyée</b>`:""}</p><div class="result">${x.result}</div></article>`).join("")||"<div class='panel'>Aucune estimation.</div>"}catch(e){box.innerHTML=`<div class="panel">Erreur : ${e.message}</div>`}}
async function renderAnalytics(){if(!qs("visitorsChart"))return;const data=await loadJSON("analytics.json",{days:[]});const labels=data.days.map(d=>d.date.slice(5));const revenue=data.days.map((d,i)=>i*12+40);drawLine("revenueChart",labels,revenue,"€");drawLine("visitorsChart",labels,data.days.map(d=>d.visitors));drawLine("viewsChart",labels,data.days.map(d=>d.views));qs("kpiVisitors").textContent=data.days.reduce((s,d)=>s+d.visitors,0);qs("kpiViews").textContent=data.days.reduce((s,d)=>s+d.views,0);qs("kpiRevenue").textContent=euro(revenue.reduce((s,n)=>s+n,0))}
function drawLine(id,labels,values,suffix=""){const c=qs(id);if(!c)return;const ctx=c.getContext("2d"),w=c.width,h=c.height,pad=45,max=Math.max(...values,1);ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(212,175,55,.25)";ctx.beginPath();ctx.moveTo(pad,pad);ctx.lineTo(pad,h-pad);ctx.lineTo(w-pad,h-pad);ctx.stroke();const pts=values.map((v,i)=>({x:pad+i*((w-2*pad)/Math.max(values.length-1,1)),y:h-pad-(v/max)*(h-2*pad),v}));ctx.strokeStyle="#ffe18a";ctx.lineWidth=4;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
window.toggleMenu=toggleMenu;window.setFilter=setFilter;window.addToCart=addToCart;window.checkoutBoutique=checkoutBoutique;window.sendCardEstimate=sendCardEstimate;window.prepareVerification=sendCardEstimate;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.setOrderFilter=setOrderFilter;window.openOrderDoc=openOrderDoc;window.loadAdminEstimations=loadAdminEstimations;
document.addEventListener("DOMContentLoaded",initCardoria);
})();
