import { Router } from "express";
import { assertSellerSession } from "../lib/marketplace/v1/security.js";
import { getLiveSession } from "../lib/live/sessions.js";
import { addLiveChatMessage, drawGiveaway, enterGiveaway, getLiveActionState, listLiveChat, pinLiveProduct, placeAuctionBid, startAuction, startBreak, startFlashSale, startGiveaway, stopAuction, unpinLiveProduct } from "../lib/live/actions.js";

const router=Router(),rateBuckets=new Map();
function fail(res,error,fallback=400){res.status(error?.status||fallback).json({ok:false,error:error?.message||"Erreur action Live",minimum:error?.minimum});}
function sellerActor(req){const seller=assertSellerSession(req);return{id:seller.id,sellerId:seller.id,role:"seller",email:seller.email};}
function assertSellerOwner(req,liveId){const actor=sellerActor(req),live=getLiveSession(liveId);if(!live)throw Object.assign(new Error("Live introuvable."),{status:404});if(live.ownerRole!=="seller"||String(live.ownerId)!==String(actor.sellerId))throw Object.assign(new Error("Ce Live appartient a un autre vendeur."),{status:403});return actor;}
function publicState(state){const copy=structuredClone(state||{});if(copy.auction){copy.auction.bids=(copy.auction.bids||[]).map(({bidderEmail,...bid})=>bid);if(copy.auction.highestBidder)delete copy.auction.highestBidder.email;}if(copy.giveaway){copy.giveaway.entries=(copy.giveaway.entries||[]).map(({email,...entry})=>entry);if(copy.giveaway.winner)delete copy.giveaway.winner.email;}return copy;}
function requireBidderEmail(body){const email=String(body?.bidderEmail||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error("Email acheteur obligatoire pour pouvoir payer l'enchere gagnee."),{status:400});return{...body,bidderEmail:email};}
function rateLimit(req,kind,limit,windowMs){const key=[kind,req.params.liveId,String(req.ip||req.socket?.remoteAddress||"unknown")].join(":");const now=Date.now(),entry=rateBuckets.get(key);if(!entry||now-entry.startedAt>=windowMs){rateBuckets.set(key,{startedAt:now,count:1});return;}entry.count++;if(entry.count>limit)throw Object.assign(new Error("Trop de requetes Live. Reessayez dans quelques secondes."),{status:429});if(rateBuckets.size>5000){for(const[k,v]of rateBuckets)if(now-v.startedAt>60_000)rateBuckets.delete(k);}}
router.get("/:liveId/state",(req,res)=>{try{const live=getLiveSession(req.params.liveId);if(!live)return res.status(404).json({ok:false,error:"Live introuvable."});res.json({ok:true,state:publicState(getLiveActionState(req.params.liveId))});}catch(e){fail(res,e);}});
router.get("/:liveId/chat",(req,res)=>{try{res.json({ok:true,messages:listLiveChat(req.params.liveId,req.query.limit)});}catch(e){fail(res,e);}});
router.post("/:liveId/chat",(req,res)=>{try{rateLimit(req,"chat",5,10_000);res.json({ok:true,message:addLiveChatMessage(req.params.liveId,req.body||{})});}catch(e){fail(res,e);}});
router.post("/:liveId/bids",(req,res)=>{try{rateLimit(req,"bid",20,10_000);const result=placeAuctionBid(req.params.liveId,requireBidderEmail(req.body||{}));res.json({ok:true,auction:publicState({auction:result.auction}).auction,bid:{id:result.bid.id,amount:result.bid.amount,bidderName:result.bid.bidderName,createdAt:result.bid.createdAt}});}catch(e){fail(res,e);}});
router.post("/:liveId/giveaway/enter",(req,res)=>{try{rateLimit(req,"giveaway",10,60_000);const result=enterGiveaway(req.params.liveId,req.body||{});res.json({ok:true,duplicate:Boolean(result.duplicate),entry:result.entry?{id:result.entry.id,name:result.entry.name,createdAt:result.entry.createdAt}:null,giveaway:publicState({giveaway:result.giveaway}).giveaway});}catch(e){fail(res,e);}});
router.post("/seller/:liveId/pin",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,state:pinLiveProduct(req.params.liveId,req.body?.productId)});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/unpin",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,state:unpinLiveProduct(req.params.liveId)});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/auction/start",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,auction:startAuction(req.params.liveId,req.body||{})});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/auction/stop",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,auction:stopAuction(req.params.liveId)});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/flash/start",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,flash:startFlashSale(req.params.liveId,req.body||{})});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/giveaway/start",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,giveaway:startGiveaway(req.params.liveId,req.body||{})});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/giveaway/draw",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,...drawGiveaway(req.params.liveId)});}catch(e){fail(res,e,401);}});
router.post("/seller/:liveId/break/start",(req,res)=>{try{assertSellerOwner(req,req.params.liveId);res.json({ok:true,break:startBreak(req.params.liveId,req.body||{})});}catch(e){fail(res,e,401);}});
export default router;
