Match User github-ops
  ForceCommand /usr/local/bin/cardoria-ops-ssh-wrapper
  AllowTcpForwarding no
  X11Forwarding no
  AllowAgentForwarding no
  PermitTTY no
  PasswordAuthentication no
  PubkeyAuthentication yes
  PermitTunnel no
