import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const sessions=fs.readFileSync(new URL("../lib/live/sessions.js",import.meta.url),"utf8");
const realtime=fs.readFileSync(new URL("../lib/live/realtime-sessions.js",import.meta.url),"utf8");
const realtimeRoutes=fs.readFileSync(new URL("../routes/live-realtime.js",import.meta.url),"utf8");
const actionRoutes=fs.readFileSync(new URL("../routes/live-actions.js",import.meta.url),"utf8");
const adminRoutes=fs.readFileSync(new URL("../routes/live-admin.js",import.meta.url),"utf8");
const sellerRoutes=fs.readFileSync(new URL("../routes/live.js",import.meta.url),"utf8");
const admin=fs.readFileSync(new URL("../../js/admin/admin-live.js",import.meta.url),"utf8");
const adminRuntime=fs.readFileSync(new URL("../public/js/admin/admin-live.js",import.meta.url),"utf8");
const seller=fs.readFileSync(new URL("../../js/live-vendeur.js",import.meta.url),"utf8");
const sellerRuntime=fs.readFileSync(new URL("../public/js/live-vendeur.js",import.meta.url),"utf8");
const ownerActions=fs.readFileSync(new URL("../../js/live-studio-actions-ui.js",import.meta.url),"utf8");
const ownerActionsRuntime=fs.readFileSync(new URL("../public/js/live-studio-actions-ui.js",import.meta.url),"utf8");
const viewerActions=fs.readFileSync(new URL("../../js/cardoria-live-actions.js",import.meta.url),"utf8");
const viewerActionsRuntime=fs.readFileSync(new URL("../public/js/cardoria-live-actions.js",import.meta.url),"utf8");
const rootLive=fs.readFileSync(new URL("../../live.html",import.meta.url),"utf8");
const runtimeLive=fs.readFileSync(new URL("../public/live.html",import.meta.url),"utf8");
const rootAdmin=fs.readFileSync(new URL("../../admin-live.html",import.meta.url),"utf8");
const runtimeAdmin=fs.readFileSync(new URL("../public/admin-live.html",import.meta.url),"utf8");
const rootSeller=fs.readFileSync(new URL("../../live-vendeur.html",import.meta.url),"utf8");
const runtimeSeller=fs.readFileSync(new URL("../public/live-vendeur.html",import.meta.url),"utf8");
const phone=fs.readFileSync(new URL("../../live-camera.html",import.meta.url),"utf8");

test("Live rooms can be created without product or price for Admin and seller",()=>{assert.match(sessions,/normalizeProducts\(raw\)\{if\(!Array\.isArray\(raw\)\|\|!raw\.length\)return \[\];/);assert.match(sessions,/products=\[\]/);assert.match(admin,/products:\[\]/);assert.match(seller,/products:\[\]/);assert.doesNotMatch(admin,/19,90|9,90|Revolut/i);assert.doesNotMatch(seller,/19\.90|9\.90|Revolut/i);});
test("payment routing is explicit: Admin SumUp, seller PayPal",()=>{assert.match(admin,/Cardoria\/Admin = SumUp/);assert.match(admin,/Vendeur tiers = PayPal/);assert.match(seller,/Paiement des ventes : PayPal/);assert.match(sellerRoutes,/provider: "paypal"/);});
test("Admin and seller studios expose live payment paid pending failed states",()=>{for(const source of[admin,seller]){assert.match(source,/Autorisé \/ Payé/);assert.match(source,/Pending \/ En attente/);assert.match(source,/Refusé \/ Échoué/);assert.match(source,/setInterval\([^,]+,3000\)/);}assert.match(adminRoutes,/router\.get\("\/checkouts"/);assert.match(sellerRoutes,/router\.get\("\/seller\/checkouts"/);});
test("all active frontend runtime mirrors are synchronized",()=>{assert.equal(adminRuntime,admin);assert.equal(sellerRuntime,seller);assert.equal(ownerActionsRuntime,ownerActions);assert.equal(viewerActionsRuntime,viewerActions);assert.equal(runtimeLive,rootLive);assert.equal(runtimeAdmin,rootAdmin);assert.equal(runtimeSeller,rootSeller);});
test("Live supports two publishers, secure phone pairing and per-Live audience count",()=>{assert.match(realtime,/MAX_PUBLISHERS_PER_LIVE\s*=\s*2/);assert.match(realtime,/createPublisherPair/);assert.match(realtime,/PAIR_TTL_MS\s*=\s*10\s*\*\s*60_000/);assert.match(realtime,/realtimeStatusForLive/);assert.match(realtime,/viewerCountForLive/);assert.match(realtimeRoutes,/\/publisher\/pair/);assert.match(realtimeRoutes,/\/status\/:liveId/);assert.match(realtimeRoutes,/pairToken/);assert.match(admin,/Caméra 2 \/ téléphone/);assert.match(admin,/Démarrer Caméra 1/);assert.match(admin,/Démarrer Caméra 2 PC/);assert.match(admin,/livePublisherPreview1/);assert.match(admin,/livePublisherPreview2/);assert.match(seller,/Caméra 2 \/ téléphone/);assert.match(phone,/pairToken:pair/);});
test("phone pair token is one-use and not stored in clear",()=>{assert.match(realtime,/createHash\("sha256"\)/);assert.match(realtime,/pair\.used\s*=\s*true/);assert.match(realtime,/publisherPairs\.delete\(hash\)/);});
test("Whatnot-style Live actions are exposed to owners and viewers",()=>{for(const word of["Achat immédiat","Enchère","Vente flash","Giveaway","Ouverture / break","Épingler"]){assert.match(ownerActions,new RegExp(word));}assert.match(viewerActions,/Enchérir/);assert.match(viewerActions,/Participer gratuitement/);assert.match(viewerActions,/Chat du Live/);assert.match(viewerActions,/Acheter un spot/);assert.match(viewerActions,/Payer le lot gagné/);});
test("public action API requires bidder email and redacts private emails",()=>{assert.match(actionRoutes,/requireBidderEmail/);assert.match(actionRoutes,/delete copy\.auction\.highestBidder\.email/);assert.match(actionRoutes,/delete copy\.giveaway\.winner\.email/);assert.match(actionRoutes,/\(\{bidderEmail,\.\.\.bid\}\)/);assert.match(actionRoutes,/\(\{email,\.\.\.entry\}\)/);});
test("active Live runtime has no Render or whatnot-live-studio dependency",()=>{const active=[sellerRoutes,realtimeRoutes,admin,seller,ownerActions,viewerActions,rootLive,rootAdmin,rootSeller].join("\n");assert.doesNotMatch(active,/whatnot-live-studio|onrender\.com|render\.com/i);});
