import assert from "node:assert/strict";
import crypto from "node:crypto";
import test from "node:test";
import { PAYMENT_MATRIX, assertSaleProvider, assertServerAmount, resolvePaymentRoute } from "../lib/payments/routing.js";
import { isSumUpConfigured, mapSumUpStatus, verifySumUpWebhookSignature, handleSumUpWebhook } from "../lib/payments/sumup.js";
import { planLiveCheckout } from "../lib/live/checkout.js";
import { __resetLiveStoreForTests, __setLiveStoreForTests, applyLivePaymentStatus } from "../lib/live/sessions.js";
function seed(){__setLiveStoreForTests({sessions:[{id:"A",title:"Admin",ownerRole:"admin",ownerId:"cardoria",status:"live",products:[{id:"P",name:"Lot",stock:3,price:20}]},{id:"S",title:"Seller",ownerRole:"seller",ownerId:"SEL",status:"live",products:[{id:"P2",name:"Lot",stock:3,price:15}]}],checkouts:[],adminAccess:[]});}
test("matrix Boutique SumUp, Live Admin SumUp, seller/marketplace PayPal",()=>{assert.deepEqual(PAYMENT_MATRIX,{boutique:"sumup",live_admin:"sumup",live_seller:"paypal",marketplace:"paypal"});assert.equal(resolvePaymentRoute({channel:"boutique"}).provider,"sumup");assert.equal(resolvePaymentRoute({channel:"live",ownerRole:"admin"}).provider,"sumup");assert.equal(resolvePaymentRoute({channel:"live",ownerRole:"seller"}).provider,"paypal");assert.equal(resolvePaymentRoute({channel:"marketplace"}).provider,"paypal");});
test("wrong providers and retired Revolut are refused",()=>{assert.throws(()=>assertSaleProvider({channel:"boutique",requestedProvider:"paypal"}),e=>e.status===403&&e.expectedProvider==="sumup");assert.throws(()=>assertSaleProvider({channel:"boutique",requestedProvider:"revolut"}),e=>e.status===410&&e.expectedProvider==="sumup");assert.throws(()=>assertSaleProvider({channel:"marketplace",requestedProvider:"sumup"}),e=>e.status===403&&e.expectedProvider==="paypal");});
test("server amount cannot be forged",()=>{assert.equal(assertServerAmount(19.9,19.9),19.9);assert.throws(()=>assertServerAmount(19.9,1),e=>e.status===403);});
test("SumUp configuration requires key and merchant",()=>{const a=process.env.SUMUP_API_KEY,b=process.env.SUMUP_MERCHANT_CODE;delete process.env.SUMUP_API_KEY;delete process.env.SUMUP_MERCHANT_CODE;assert.equal(isSumUpConfigured(),false);process.env.SUMUP_API_KEY="x";process.env.SUMUP_MERCHANT_CODE="m";assert.equal(isSumUpConfigured(),true);if(a==null)delete process.env.SUMUP_API_KEY;else process.env.SUMUP_API_KEY=a;if(b==null)delete process.env.SUMUP_MERCHANT_CODE;else process.env.SUMUP_MERCHANT_CODE=b;});
test("SumUp status mapping",()=>{assert.equal(mapSumUpStatus("SUCCESSFUL"),"paid");assert.equal(mapSumUpStatus("DECLINED"),"failed");assert.equal(mapSumUpStatus("REFUNDED"),"refunded");assert.equal(mapSumUpStatus("PENDING"),"pending");});
test("SumUp webhook signature invalid is rejected before network",async()=>{const old=process.env.SUMUP_WEBHOOK_SECRET;process.env.SUMUP_WEBHOOK_SECRET="secret";const raw=Buffer.from(JSON.stringify({id:"x"}));assert.equal(verifySumUpWebhookSignature(raw,"deadbeef"),false);await assert.rejects(handleSumUpWebhook(raw,"deadbeef"),e=>e.status===401);if(old==null)delete process.env.SUMUP_WEBHOOK_SECRET;else process.env.SUMUP_WEBHOOK_SECRET=old;});
test("SumUp webhook without checkout is safely ignored",async()=>{const old=process.env.SUMUP_WEBHOOK_SECRET;delete process.env.SUMUP_WEBHOOK_SECRET;const r=await handleSumUpWebhook(Buffer.from("{}"),"");assert.equal(r.received,true);assert.equal(r.ignored,true);if(old!=null)process.env.SUMUP_WEBHOOK_SECRET=old;});
test("Live admin uses SumUp with zero commission; seller keeps PayPal commission",()=>{seed();const a=planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"a@b.fr"});assert.equal(a.provider,"sumup");assert.equal(a.platformFee,0);const s=planLiveCheckout({liveId:"S",productId:"P2",qty:1,customerEmail:"s@b.fr"});assert.equal(s.provider,"paypal");assert.ok(s.platformFee>0);__resetLiveStoreForTests();});
test("frontend cannot reroute Live payments",()=>{seed();assert.throws(()=>planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"a@b.fr",requestedProvider:"paypal"}),e=>e.status===403&&e.expectedProvider==="sumup");assert.throws(()=>planLiveCheckout({liveId:"S",productId:"P2",qty:1,customerEmail:"s@b.fr",requestedProvider:"sumup"}),e=>e.status===403&&e.expectedProvider==="paypal");assert.throws(()=>planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"a@b.fr",requestedProvider:"revolut"}),e=>e.status===410&&e.expectedProvider==="sumup");__resetLiveStoreForTests();});
test("Live idempotence protects duplicate payment and stock",()=>{seed();const a=planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"same@b.fr"}),b=planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"same@b.fr"});assert.equal(a.id,b.id);applyLivePaymentStatus(a.id,"paid");const again=applyLivePaymentStatus(a.id,"paid");assert.equal(again.alreadyPaid,true);assert.throws(()=>planLiveCheckout({liveId:"A",productId:"P",qty:1,customerEmail:"same@b.fr"}),e=>e.status===409);__resetLiveStoreForTests();});
test("valid SumUp signature is deterministic",()=>{const old=process.env.SUMUP_WEBHOOK_SECRET;process.env.SUMUP_WEBHOOK_SECRET="secret";const raw=Buffer.from('{"x":1}'),sig=crypto.createHmac("sha256","secret").update(raw).digest("hex");assert.equal(verifySumUpWebhookSignature(raw,sig),true);if(old==null)delete process.env.SUMUP_WEBHOOK_SECRET;else process.env.SUMUP_WEBHOOK_SECRET=old;});
