import { slugifyExtensionName } from "./sitemap-urls.js";

const htmlEscape = (value = '') => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

export function positivePrice(value) {
  if (typeof value !== 'number' && typeof value !== 'string') return null;
  if (typeof value === 'string' && !value.trim()) return null;
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? number : null;
}

export function safeImage(value) {
  try {
    const url = new URL(String(value || ''));
    return ['https:', 'http:'].includes(url.protocol) && !url.username && !url.password ? url.href : '';
  } catch { return ''; }
}

export function cardImageAlt(card = {}) {
  const languageCodes = { fr: 'FR', en: 'EN', ja: 'JP', ko: 'KR' };
  const language = languageCodes[String(card.language || 'fr').toLowerCase()] || String(card.language || '').toUpperCase();
  const license = String(card.licenseName || card.license || card.licenseSlug || 'TCG').trim();
  const identity = [card.name, card.number, card.extension].map((value) => String(value || '').trim()).filter(Boolean).join(' ');
  return [identity, `Carte ${license}${language ? ' ' + language : ''}`].filter(Boolean).join(' — ');
}

export function cardExtensionUrl(card = {}) {
  const license = String(card.license || card.licenseSlug || "pokemon").trim();
  const extensionSlug = slugifyExtensionName(card.extension);
  if (!/^[a-z0-9-]+$/.test(license) || !extensionSlug) return "";
  return `/extensions/${encodeURIComponent(license)}/${encodeURIComponent(extensionSlug)}`;
}

function cardLanguageLabel(language = "fr") {
  return {
    fr: "française",
    en: "anglaise",
    ja: "japonaise",
    ko: "coréenne"
  }[String(language || "fr").toLowerCase()] || String(language || "").trim();
}

function attribute(tag, name) {
  return new RegExp('\\b' + name + '\\s*=\\s*(?:"([^"]*)"|\'([^\']*)\')', 'i').exec(tag)?.slice(1).find((value) => value !== undefined) || '';
}

// Only clean public templates whose metadata is regenerated by the server.
// Keep verification, explicit crawl restrictions, CSS, icons and scripts.
export function cleanSeoTemplate(template) {
  return String(template).replace(/<head\b[^>]*>[\s\S]*?<\/head>/i, (head) => head
    .replace(/<link\b[^>]*>/gi, (tag) => attribute(tag, 'rel').toLowerCase() === 'canonical' ? '' : tag)
    .replace(/<meta\b[^>]*>/gi, (tag) => {
      const name = attribute(tag, 'name').toLowerCase();
      const property = attribute(tag, 'property').toLowerCase();
      if ((name === 'robots' || name === 'googlebot') && /\b(?:noindex|nofollow|none|nosnippet|noimageindex|unavailable_after)\b/i.test(attribute(tag, 'content'))) return tag;
      return name === 'robots' || name === 'googlebot' || name === 'cardoria:server-seo' || name.startsWith('twitter:') || property.startsWith('og:') ? '' : tag;
    })
    // The marker precedes the synchronous generic SEO script, preventing it
    // from changing a card/extension canonical to the homepage URL.
    .replace(/<head\b[^>]*>/i, (opening) => opening + '\n<meta name="cardoria:server-seo" content="true">')
  ).replace(/\bhref=(['"])([a-z0-9-]+\.html(?:[?#][^'"<>]*)?)\1/gi, (_match, quote, target) => {
    const normalized = target === 'index.html' ? '/' : '/' + target;
    return `href=${quote}${normalized}${quote}`;
  });
}

// Reference data, not a stock listing: do not create Offer/AggregateOffer or
// imply that a card is for sale. Missing market data must not become a zero price.
export function renderCardMain(card) {
  const license = card.license || card.licenseSlug || 'pokemon';
  const licenseName = card.licenseName || license;
  const name = card.name || 'Carte';
  const languageLabel = cardLanguageLabel(card.language);
  const extensionUrl = cardExtensionUrl(card);
  const detail = (label, value) => `<div class="engine-meta-item"><label>${htmlEscape(label)}</label><strong>${htmlEscape(value || 'Non renseigné')}</strong></div>`;
  const detailHtml = (label, valueHtml) => `<div class="engine-meta-item"><label>${htmlEscape(label)}</label><strong>${valueHtml}</strong></div>`;
  const money = (value) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(value);
  const prices = card.prices || {};
  const priceBox = (label, value, recommended = false) => {
    const amount = positivePrice(value);
    return `<div class="engine-price-box${recommended ? ' recommended' : ''}"><label>${htmlEscape(label)}</label><strong>${amount === null ? 'Non disponible' : htmlEscape(money(amount))}</strong></div>`;
  };
  const image = safeImage(card.imageHd) || safeImage(card.imageThumb);
  const visual = image
    ? `<img src="${htmlEscape(image)}" alt="${htmlEscape(cardImageAlt(card))}" loading="eager" fetchpriority="high" width="360" height="504">`
    : '<div class="placeholder" aria-label="Visuel indisponible">Visuel indisponible</div>';
  const extensionDetail = extensionUrl
    ? detailHtml('Extension', `<a href="${extensionUrl}">${htmlEscape(card.extension)}</a>`)
    : detail('Extension', card.extension);
  const breadcrumbExtension = extensionUrl
    ? ` › <a href="${extensionUrl}">${htmlEscape(card.extension)}</a>`
    : "";
  const identity = [name, card.number].filter(Boolean).join(' ');
  const heading = [identity || name, card.extension].map((value) => String(value || '').trim()).filter(Boolean).join(' — ');
  const leadParts = [
    `${htmlEscape(identity)} est une carte ${htmlEscape(licenseName)}`,
    languageLabel ? `en version ${htmlEscape(languageLabel)}` : "",
    card.extension ? `de l’extension ${htmlEscape(card.extension)}` : "",
    card.rarity ? `de rareté ${htmlEscape(card.rarity)}` : ""
  ].filter(Boolean);
  return `<main class="container engine-hero" id="cardPage" data-server-rendered="true">
<nav class="engine-breadcrumb" aria-label="Fil d’Ariane"><a href="/">Accueil</a> › <a href="/pages/licences/${encodeURIComponent(license)}/">${htmlEscape(licenseName)}</a>${breadcrumbExtension} › ${htmlEscape(name)}</nav>
<h1>${htmlEscape(heading)}</h1>
<p class="seo-lead">${leadParts.join(' ') }.</p>
<div class="engine-card-layout"><div class="engine-card-visual">${visual}</div><div>
<div class="engine-meta-grid">${extensionDetail}${detail('Numéro', card.number)}${detail('Langue', languageLabel)}${detail('Rareté', card.rarity)}${detail('Illustrateur', card.illustration)}${detail('État réf.', card.condition)}${detail('Licence', licenseName)}</div>
<div class="engine-prices">${priceBox('Prix moyen', prices.avg)}${priceBox('Prix bas', prices.low)}${priceBox('Prix haut', prices.high)}${priceBox('Prix conseillé', prices.recommended, true)}</div>
<p class="small">Données de référence lorsqu’elles sont disponibles, et non une offre de vente. La valeur dépend notamment de l’état, de la langue et de la version de la carte.</p>
<div class="actions" style="margin-top:18px"><a class="btn btn-primary" href="/estimation.html?card=${encodeURIComponent(card.id || '')}">Faire estimer cette carte</a> <a class="btn btn-secondary" href="/rachat-cartes.html">Vendre à Cardoria</a></div>
</div></div></main>`;
}
