/** Actions temps reel du Studio Live Cardoria (sans dependance Render). */
import crypto from "crypto";
import { readJson, writeJson } from "../storage.js";
import { decrementLiveStock, getLiveSession } from "./sessions.js";

const STORE_KEY="live-actions.json";let testStore=null;
const clean=(v,max=240)=>String(v==null?"":v).trim().slice(0,max),money=(v)=>Math.round((Number(v)||0)*100)/100,nowIso=()=>new Date().toISOString();
function emptyStore(){return{states:{}};}function load(){const d=testStore||readJson(STORE_KEY,emptyStore());if(!d.states||typeof d.states!=="object")d.states={};return d;}function save(d){if(testStore){Object.assign(testStore,d);return;}writeJson(STORE_KEY,d);}function stateFor(liveId,create=false){const d=load();let state=d.states[liveId];if(!state&&create){state={pinnedProductId:"",auction:null,flash:null,giveaway:null,break:null,chat:[],updatedAt:nowIso()};d.states[liveId]=state;save(d);}return{d,state};}
function requireLive(liveId){const live=getLiveSession(liveId);if(!live)throw Object.assign(new Error("Live introuvable."),{status:404});if(live.status!=="live")throw Object.assign(new Error("Le Live doit etre demarre."),{status:409});return live;}function productFor(live,productId){const product=(live.products||[]).find((p)=>p.id===String(productId||""));if(!product)throw Object.assign(new Error("Produit Live introuvable."),{status:404});return product;}function publicEmail(value){const e=clean(value,254).toLowerCase();if(e&&!/^\S+@\S+\.\S+$/.test(e))throw Object.assign(new Error("Adresse email invalide."),{status:400});return e;}
function closeExpired(state){const now=Date.now();if(state?.auction?.status==="running"&&new Date(state.auction.endsAt).getTime()<=now){state.auction.status="ended";state.auction.endedAt=state.auction.endedAt||nowIso();}if(state?.flash?.status==="running"&&new Date(state.flash.endsAt).getTime()<=now){state.flash.status="ended";state.flash.endedAt=state.flash.endedAt||nowIso();}if(state?.giveaway?.status==="running"&&new Date(state.giveaway.endsAt).getTime()<=now)state.giveaway.status="ready_to_draw";}
function refreshBreakProgress(liveId,state){if(!state?.break)return;const live=getLiveSession(liveId),product=(live?.products||[]).find((p)=>p.id===state.break.productId);if(!product)return;const start=Number(state.break.stockAtStart??state.break.spots),remainingStock=Math.max(0,Number(product.stock||0)),sold=Math.max(0,Math.min(Number(state.break.spots||0),start-remainingStock));state.break.soldSpots=sold;state.break.remainingSpots=Math.max(0,Number(state.break.spots||0)-sold);if(state.break.remainingSpots===0&&state.break.status==="running"){state.break.status="sold_out";state.break.endedAt=nowIso();}}
export function __setLiveActionsStoreForTests(store){testStore=store||emptyStore();}export function __resetLiveActionsStoreForTests(){testStore=null;}
export function getLiveActionState(liveId){const{d,state}=stateFor(String(liveId||""),true);closeExpired(state);refreshBreakProgress(liveId,state);state.updatedAt=nowIso();save(d);return structuredClone(state);}
export function pinLiveProduct(liveId,productId){const live=requireLive(liveId);productFor(live,productId);const{d,state}=stateFor(live.id,true);state.pinnedProductId=String(productId);state.updatedAt=nowIso();save(d);return structuredClone(state);}export function unpinLiveProduct(liveId){requireLive(liveId);const{d,state}=stateFor(liveId,true);state.pinnedProductId="";state.updatedAt=nowIso();save(d);return structuredClone(state);}
export function startAuction(liveId,{productId,startPrice,durationSeconds=30,mode="standard"}={}){const live=requireLive(liveId),product=productFor(live,productId),start=money(startPrice||product.price);if(start<=0)throw Object.assign(new Error("Prix de depart invalide."),{status:400});const duration=Math.max(5,Math.min(3600,Math.trunc(Number(durationSeconds)||30))),auctionMode=String(mode).toLowerCase()==="sudden_death"?"sudden_death":"standard",{d,state}=stateFor(live.id,true);if(state.auction?.status==="running")throw Object.assign(new Error("Une enchere est deja en cours."),{status:409});const started=Date.now();state.pinnedProductId=product.id;state.auction={id:"AUC-"+crypto.randomUUID(),productId:product.id,productName:product.name,status:"running",mode:auctionMode,startPrice:start,currentPrice:start,highestBidder:null,bids:[],startedAt:new Date(started).toISOString(),endsAt:new Date(started+duration*1000).toISOString(),durationSeconds:duration};state.updatedAt=nowIso();save(d);return structuredClone(state.auction);}
export function placeAuctionBid(liveId,{amount,bidderName,bidderEmail}={}){requireLive(liveId);const{d,state}=stateFor(liveId,true);closeExpired(state);const a=state.auction;if(!a||a.status!=="running")throw Object.assign(new Error("Aucune enchere active."),{status:409});const bid=money(amount),minimum=a.bids.length?money(a.currentPrice+0.5):a.startPrice;if(bid<minimum)throw Object.assign(new Error(`Enchere minimale : ${minimum.toFixed(2)} EUR.`),{status:409,minimum});const name=clean(bidderName,80)||"Acheteur",email=publicEmail(bidderEmail),entry={id:"BID-"+crypto.randomUUID(),amount:bid,bidderName:name,bidderEmail:email,createdAt:nowIso()};a.bids.push(entry);a.currentPrice=bid;a.highestBidder={name,email};if(a.mode==="standard"){const remaining=new Date(a.endsAt).getTime()-Date.now();if(remaining<=10_000)a.endsAt=new Date(Date.now()+10_000).toISOString();}state.updatedAt=nowIso();save(d);return{auction:structuredClone(a),bid:entry};}
export function stopAuction(liveId){requireLive(liveId);const{d,state}=stateFor(liveId,true);if(!state.auction)throw Object.assign(new Error("Aucune enchere."),{status:404});closeExpired(state);if(state.auction.status==="running")state.auction.status="ended";state.auction.endedAt=state.auction.endedAt||nowIso();state.updatedAt=nowIso();save(d);return structuredClone(state.auction);}
export function startFlashSale(liveId,{productId,price,durationSeconds=60}={}){const live=requireLive(liveId),product=productFor(live,productId),flashPrice=money(price||product.price);if(flashPrice<=0)throw Object.assign(new Error("Prix flash invalide."),{status:400});const duration=Math.max(5,Math.min(3600,Math.trunc(Number(durationSeconds)||60))),started=Date.now(),{d,state}=stateFor(live.id,true);state.pinnedProductId=product.id;state.flash={id:"FLASH-"+crypto.randomUUID(),productId:product.id,productName:product.name,price:flashPrice,status:"running",startedAt:new Date(started).toISOString(),endsAt:new Date(started+duration*1000).toISOString()};state.updatedAt=nowIso();save(d);return structuredClone(state.flash);}
export function startGiveaway(liveId,{productId,durationSeconds=60}={}){const live=requireLive(liveId),product=productFor(live,productId);if(Number(product.stock||0)<1)throw Object.assign(new Error("Stock giveaway insuffisant."),{status:409});const duration=Math.max(5,Math.min(3600,Math.trunc(Number(durationSeconds)||60))),started=Date.now(),{d,state}=stateFor(live.id,true);state.pinnedProductId=product.id;state.giveaway={id:"GIV-"+crypto.randomUUID(),productId:product.id,productName:product.name,status:"running",entries:[],winner:null,stockConsumed:false,startedAt:new Date(started).toISOString(),endsAt:new Date(started+duration*1000).toISOString()};state.updatedAt=nowIso();save(d);return structuredClone(state.giveaway);}
export function enterGiveaway(liveId,{name,email}={}){requireLive(liveId);const{d,state}=stateFor(liveId,true),g=state.giveaway;closeExpired(state);if(!g||g.status!=="running")throw Object.assign(new Error("Giveaway ferme."),{status:409});const e=publicEmail(email),n=clean(name,80)||"Participant";if(e&&g.entries.some((x)=>x.email===e))return{duplicate:true,entry:g.entries.find((x)=>x.email===e),giveaway:structuredClone(g)};const entry={id:"ENT-"+crypto.randomUUID(),name:n,email:e,createdAt:nowIso()};g.entries.push(entry);state.updatedAt=nowIso();save(d);return{entry,giveaway:structuredClone(g)};}
export function drawGiveaway(liveId){requireLive(liveId);const{d,state}=stateFor(liveId,true),g=state.giveaway;if(!g)throw Object.assign(new Error("Aucun giveaway."),{status:404});if(!g.entries.length)throw Object.assign(new Error("Aucun participant."),{status:409});if(g.winner)return{duplicate:true,giveaway:structuredClone(g)};const index=crypto.randomInt(g.entries.length);g.winner=g.entries[index];g.status="ended";g.endedAt=nowIso();if(!g.stockConsumed){decrementLiveStock(liveId,g.productId,1);g.stockConsumed=true;}state.updatedAt=nowIso();save(d);return{giveaway:structuredClone(g)};}
export function startBreak(liveId,{productId,spots=1,pricePerSpot}={}){const live=requireLive(liveId),product=productFor(live,productId),count=Math.max(1,Math.min(1000,Math.trunc(Number(spots)||product.qty||1))),price=money(pricePerSpot||product.price);if(price<=0)throw Object.assign(new Error("Prix du spot invalide."),{status:400});if(Number(product.stock||0)<count)throw Object.assign(new Error("Stock insuffisant pour le nombre de spots."),{status:409});const{d,state}=stateFor(live.id,true);state.pinnedProductId=product.id;state.break={id:"BRK-"+crypto.randomUUID(),productId:product.id,productName:product.name,status:"running",spots:count,pricePerSpot:price,stockAtStart:Number(product.stock||0),soldSpots:0,remainingSpots:count,startedAt:nowIso()};state.updatedAt=nowIso();save(d);return structuredClone(state.break);}
export function addLiveChatMessage(liveId,{name,message}={}){requireLive(liveId);const text=clean(message,500);if(!text)throw Object.assign(new Error("Message vide."),{status:400});const{d,state}=stateFor(liveId,true),entry={id:"MSG-"+crypto.randomUUID(),name:clean(name,80)||"Spectateur",message:text,createdAt:nowIso()};state.chat.push(entry);state.chat=state.chat.slice(-200);state.updatedAt=nowIso();save(d);return entry;}export function listLiveChat(liveId,limit=50){requireLive(liveId);const{state}=stateFor(liveId,true);return structuredClone((state.chat||[]).slice(-Math.max(1,Math.min(200,Number(limit)||50))));}
