/** Checkout Live Cardoria : Live Admin → SumUp, Live vendeur → PayPal. */
import crypto from "crypto";
import { assertSaleProvider, assertServerAmount, money } from "../payments/routing.js";
import { createSumUpCheckout, isSumUpConfigured } from "../payments/sumup.js";
import { getPayPalMarketplaceConfig, createLivePayPalOrder } from "../marketplace/paypal.js";
import { getLiveCommissionAmount, getSellerPlan } from "../subscriptions/plans.js";
import { getSellerPlanState } from "../subscriptions/seller-plans.js";
import { getLiveCheckout, getLiveSession, listLiveCheckouts, saveLiveCheckout, withLiveLock } from "./sessions.js";
import { resolveLiveSaleRule } from "./sale-rules.js";
const clean=(v,m=200)=>String(v==null?"":v).trim().slice(0,m);
function validateEmail(v){const e=clean(v,254).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(e))throw Object.assign(new Error("Adresse email invalide."),{status:400});return e;}
function commissionFor(live,amount){if(live.ownerRole!=="seller")return{platformFee:0,sellerNet:amount,commissionPercent:0};try{const state=getSellerPlanState(live.ownerId),plan=getSellerPlan(state.planId),platformFee=money(getLiveCommissionAmount(state.planId,amount));return{platformFee,sellerNet:money(amount-platformFee),commissionPercent:Number(plan.liveCommissionRate)*100,planId:plan.id};}catch{const percent=5,platformFee=money(amount*percent/100);return{platformFee,sellerNet:money(amount-platformFee),commissionPercent:percent};}}
function reservedUnits(liveId,productId,excludeKey=""){return listLiveCheckouts({liveId}).filter((c)=>c.productId===productId&&c.idempotencyKey!==excludeKey&&["planned","pending"].includes(c.status)).reduce((n,c)=>n+Math.max(1,Number(c.qty)||1),0);}
function normalizeSpotLabel(value){return clean(value,80);}
function assertEnergySpotAvailable({liveId,productId,rule,spotLabel,excludeKey}){
  if(rule.breakType!=="energy_game") return "";
  const label=normalizeSpotLabel(spotLabel);
  if(!label) throw Object.assign(new Error("Choisissez une énergie disponible avant le paiement."),{status:400});
  const canonical=(rule.spotLabels||[]).find((item)=>String(item)===label);
  if(!canonical) throw Object.assign(new Error("Cette énergie ne fait pas partie de l'item sélectionné."),{status:409});
  const occupied=listLiveCheckouts({liveId}).some((c)=>c.productId===productId&&c.idempotencyKey!==excludeKey&&String(c.spotLabel||"")===canonical&&["planned","pending","paid","completed","authorized","authorised"].includes(String(c.status||"").toLowerCase()));
  if(occupied) throw Object.assign(new Error(`Le spot ${canonical} est déjà réservé ou vendu.`),{status:409,spotLabel:canonical});
  return canonical;
}
export function planLiveCheckout({liveId,productId,qty,spotLabel,customerEmail,customerName,requestedProvider,requestedAmount}){const live=getLiveSession(liveId);if(!live)throw Object.assign(new Error("Live introuvable."),{status:404});if(live.status!=="live")throw Object.assign(new Error("Ce Live doit être en cours pour accepter un paiement."),{status:409});const route=assertSaleProvider({channel:"live",ownerRole:live.ownerRole,requestedProvider}),product=(live.products||[]).find(i=>i.id===String(productId||""));if(!product)throw Object.assign(new Error("Produit Live introuvable."),{status:404});let units=Math.max(1,Math.min(20,Math.trunc(Number(qty)||1)));const email=validateEmail(customerEmail),rule=resolveLiveSaleRule({live,product,customerEmail:email});if(rule.breakType==="energy_game")units=1;const provisionalKey=[live.id,product.id,email,units,rule.actionId||rule.kind,normalizeSpotLabel(spotLabel)].join(":"),selectedSpot=assertEnergySpotAvailable({liveId:live.id,productId:product.id,rule,spotLabel,excludeKey:provisionalKey}),idempotencyKey=[live.id,product.id,email,units,rule.actionId||rule.kind,selectedSpot].join(":"),existing=getLiveCheckout(idempotencyKey);if(existing){if(existing.status==="paid")throw Object.assign(new Error("Ce paiement Live a déjà été traité."),{status:409});if(["pending","planned"].includes(existing.status))return existing;}const available=Math.max(0,Number(product.stock||0)-reservedUnits(live.id,product.id,idempotencyKey));if(available<units)throw Object.assign(new Error(`Stock Live insuffisant pour ${product.name}.`),{status:409,available});const amount=assertServerAmount(money(rule.unitPrice)*units,requestedAmount),name=clean(customerName,120)||"Client Live",commission=commissionFor(live,amount);return saveLiveCheckout({id:"LCK-"+crypto.randomUUID(),idempotencyKey,liveId:live.id,liveTitle:live.title,ownerRole:live.ownerRole,ownerId:live.ownerId,channel:route.channel,provider:route.provider,productId:product.id,productName:product.name,qty:units,unitPrice:rule.unitPrice,saleKind:rule.kind,actionId:rule.actionId||"",breakType:rule.breakType||"",spotLabel:selectedSpot,amount,...commission,customerEmail:email,customerName:name,status:"planned",paymentProviderOrderId:"",url:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
export async function createLiveCheckout(input){const planned=planLiveCheckout(input);return withLiveLock(planned.idempotencyKey,async()=>{const current=getLiveCheckout(planned.id)||planned;if(current.status==="paid")throw Object.assign(new Error("Ce paiement Live a déjà été traité."),{status:409});if(current.url&&current.paymentProviderOrderId&&current.status==="pending")return current;if(current.provider==="sumup"){if(!isSumUpConfigured())throw Object.assign(new Error("Paiement SumUp non configuré côté serveur."),{status:503,provider:"sumup"});const payment=await createSumUpCheckout({orderId:current.id,amount:current.amount,description:`Live Cardoria — ${current.productName}${current.spotLabel?` — ${current.spotLabel}`:""}`,customerEmail:current.customerEmail,redirectUrl:String(input.successUrl||"/live.html"),source:"live_cardoria"});current.status="pending";current.paymentProviderOrderId=payment.checkoutId;current.url=payment.url;current.environment="production";current.updatedAt=new Date().toISOString();return saveLiveCheckout(current);}const paypal=getPayPalMarketplaceConfig();if(!paypal.configured)throw Object.assign(new Error("Paiement PayPal non configuré côté serveur."),{status:503,provider:"paypal"});const payment=await createLivePayPalOrder({checkoutId:current.id,amount:current.amount,sellerId:current.ownerId,description:`Live vendeur Cardoria — ${current.productName}${current.spotLabel?` — ${current.spotLabel}`:""}`,successUrl:String(input.successUrl||"/live.html"),cancelUrl:String(input.cancelUrl||"/live.html"),platformFee:current.platformFee});current.status="pending";current.paymentProviderOrderId=payment.id;current.url=payment.url;current.environment=paypal.environment;current.updatedAt=new Date().toISOString();return saveLiveCheckout(current);});}
