/** Checkout Live Cardoria : Live Admin → SumUp, Live vendeur → PayPal. */
import crypto from "crypto";
import { assertSaleProvider, assertServerAmount, money } from "../payments/routing.js";
import { createSumUpCheckout, isSumUpConfigured } from "../payments/sumup.js";
import { getPayPalMarketplaceConfig, createLivePayPalOrder } from "../marketplace/paypal.js";
import { getLiveCommissionAmount, getSellerPlan } from "../subscriptions/plans.js";
import { getSellerPlanState } from "../subscriptions/seller-plans.js";
import { getLiveCheckout, getLiveSession, saveLiveCheckout, withLiveLock } from "./sessions.js";
import { resolveLiveSaleRule } from "./sale-rules.js";
const clean=(v,m=200)=>String(v==null?"":v).trim().slice(0,m);
function validateEmail(v){const e=clean(v,254).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(e))throw Object.assign(new Error("Adresse email invalide."),{status:400});return e;}
function commissionFor(live,amount){if(live.ownerRole!=="seller")return{platformFee:0,sellerNet:amount,commissionPercent:0};try{const state=getSellerPlanState(live.ownerId),plan=getSellerPlan(state.planId),platformFee=money(getLiveCommissionAmount(state.planId,amount));return{platformFee,sellerNet:money(amount-platformFee),commissionPercent:Number(plan.liveCommissionRate)*100,planId:plan.id};}catch{const percent=5,platformFee=money(amount*percent/100);return{platformFee,sellerNet:money(amount-platformFee),commissionPercent:percent};}}
export function planLiveCheckout({liveId,productId,qty,customerEmail,customerName,requestedProvider,requestedAmount}){const live=getLiveSession(liveId);if(!live)throw Object.assign(new Error("Live introuvable."),{status:404});if(["cancelled","ended"].includes(live.status))throw Object.assign(new Error("Ce Live n'accepte plus de paiement."),{status:409});const route=assertSaleProvider({channel:"live",ownerRole:live.ownerRole,requestedProvider});const product=(live.products||[]).find(i=>i.id===String(productId||""));if(!product)throw Object.assign(new Error("Produit Live introuvable."),{status:404});const units=Math.max(1,Math.min(20,Math.trunc(Number(qty)||1)));if(Number(product.stock||0)<units)throw Object.assign(new Error(`Stock Live insuffisant pour ${product.name}.`),{status:409});const email=validateEmail(customerEmail),rule=resolveLiveSaleRule({live,product,customerEmail:email}),amount=assertServerAmount(money(rule.unitPrice)*units,requestedAmount),name=clean(customerName,120)||"Client Live",commission=commissionFor(live,amount),idempotencyKey=[live.id,product.id,email,units,rule.actionId||rule.kind].join(":");const existing=getLiveCheckout(idempotencyKey);if(existing){if(existing.status==="paid")throw Object.assign(new Error("Ce paiement Live a déjà été traité."),{status:409});if(["pending","planned"].includes(existing.status))return existing;}return saveLiveCheckout({id:"LCK-"+crypto.randomUUID(),idempotencyKey,liveId:live.id,liveTitle:live.title,ownerRole:live.ownerRole,ownerId:live.ownerId,channel:route.channel,provider:route.provider,productId:product.id,productName:product.name,qty:units,unitPrice:rule.unitPrice,saleKind:rule.kind,actionId:rule.actionId||"",amount,...commission,customerEmail:email,customerName:name,status:"planned",paymentProviderOrderId:"",url:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
export async function createLiveCheckout(input){const planned=planLiveCheckout(input);return withLiveLock(planned.idempotencyKey,async()=>{const current=getLiveCheckout(planned.id)||planned;if(current.status==="paid")throw Object.assign(new Error("Ce paiement Live a déjà été traité."),{status:409});if(current.url&&current.paymentProviderOrderId&&current.status==="pending")return current;if(current.provider==="sumup"){if(!isSumUpConfigured())throw Object.assign(new Error("Paiement SumUp non configuré côté serveur."),{status:503,provider:"sumup"});const payment=await createSumUpCheckout({orderId:current.id,amount:current.amount,description:`Live Cardoria — ${current.productName}`,customerEmail:current.customerEmail,redirectUrl:String(input.successUrl||"/live.html"),source:"live_cardoria"});current.status="pending";current.paymentProviderOrderId=payment.checkoutId;current.url=payment.url;current.environment="production";current.updatedAt=new Date().toISOString();return saveLiveCheckout(current);}const paypal=getPayPalMarketplaceConfig();if(!paypal.configured)throw Object.assign(new Error("Paiement PayPal non configuré côté serveur."),{status:503,provider:"paypal"});const payment=await createLivePayPalOrder({checkoutId:current.id,amount:current.amount,sellerId:current.ownerId,description:`Live vendeur Cardoria — ${current.productName}`,successUrl:String(input.successUrl||"/live.html"),cancelUrl:String(input.cancelUrl||"/live.html"),platformFee:current.platformFee});current.status="pending";current.paymentProviderOrderId=payment.id;current.url=payment.url;current.environment=paypal.environment;current.updatedAt=new Date().toISOString();return saveLiveCheckout(current);});}
